### ISSUE TITLE
COCO2017训练结果与论文中不同？

### ISSUE THREAD

**Issue by LZHhAG** [BICLab/SpikeYOLO#11]
作者您好，我按照您给的代码配置了环境，用COCO2017数据集进行训练，但训练结果和您在论文中给的结果有差异，不知道您这套代码，默认设置的T和D都是多少呢？
![image](https://github.com/user-attachments/assets/86cda677-0f4c-4660-af78-c83899cdbd8c)
![image](https://github.com/user-attachments/assets/97777ff9-b3ed-45c4-8f37-46241b44cc35)

**Comment by XinhaoLuo666** [comment]
您好，代码默认的T和D应该是1和4。我怀疑您的训练没有完全收敛，请问您训练了多少epoch呢？我们论文中训练了300ep。

**Comment by LZHhAG** [comment]
我训练了100个epoch，看来是要再训练一下了，谢谢您的回答。另外您代码中默认设置的T和D在哪里可以修改呢？我是初学者，确实还没有找到。望您赐教，谢谢。

**Comment by jikerWRN** [comment]
代码中T 默认是4 吧

```
class MS_GetT(nn.Module):
    def __init__(self, in_channels=1, out_channels=1, T=4):
        super().__init__()
        self.T = T
        self.in_channels = in_channels

    def forward(self, x):
        x = (x.unsqueeze(0)).repeat(self.T, 1, 1, 1, 1)
        return x
```

**Comment by XinhaoLuo666** [comment]
默认T是1，写在了config里，具体位置应该是ultralytics/cfg/models/v8/snnyolov8.yaml中，修改“MS_GetT”的参数；d的值写在了MultiSpike4函数中，请修改这个函数

**Comment by jikerWRN** [comment]
感谢您的回复~

**Comment by zhangfzR** [comment]
> 代码中T 默认是4 吧
> 
> ```
> class MS_GetT(nn.Module):
>     def __init__(self, in_channels=1, out_channels=1, T=4):
>         super().__init__()
>         self.T = T
>         self.in_channels = in_channels
> 
>     def forward(self, x):
>         x = (x.unsqueeze(0)).repeat(self.T, 1, 1, 1, 1)
>         return x
> ```
你好，你有跑通这个代码吗？请问它的训练时间是多少啊

**Comment by zhangfzR** [comment]
> 作者您好，我按照您给的代码配置了环境，用COCO2017数据集进行训练，但训练结果和您在论文中给的结果有差异，不知道您这套代码，默认设置的T和D都是多少呢？ ![image](https://private-user-images.githubusercontent.com/67531605/377459545-86cda677-0f4c-4660-af78-c83899cdbd8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDk1NDgsIm5iZiI6MTcyOTkwOTI0OCwicGF0aCI6Ii82NzUzMTYwNS8zNzc0NTk1NDUtODZjZGE2NzctMGY0Yy00NjYwLWFmNzgtYzgzODk5Y2RiZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAyMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OTM1MmQ4MWJmZGQ5NmQwODYyYzJmZmZmZmVjNzY3ZTliNTFiMzQzOGRhNzUwODFjYjM5MjhjZjhhYjZkODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ND8ndqF5AdgCsQk4Nx8kmg2gvQmcp7Cj7Y8cN9RO82E) ![image](https://private-user-images.githubusercontent.com/67531605/377459652-97777ff9-b3ed-45c4-8f37-46241b44cc35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDk1NDgsIm5iZiI6MTcyOTkwOTI0OCwicGF0aCI6Ii82NzUzMTYwNS8zNzc0NTk2NTItOTc3NzdmZjktYjNlZC00NWM0LThmMzctNDYyNDFiNDRjYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAyMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2Y4MjNmYTE0MmE3Y2Q2YzcxODcyYmQ5MmY5ODQzN2NhOGRlZDhjZGUyNDlkMmI2YmVlZGU5ZDAwOWVlNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NNt5FjkxKzw6RmjXVyKR1C804TF7TpWPyk3xKeKoePg)

你好，你有跑通这个代码吗？请问它的训练时间是多少啊

**Comment by XinhaoLuo666** [comment]
> > 作者您好，我按照您给的代码配置了环境，用COCO2017数据集进行训练，但训练结果和您在论文中给的结果有差异，不知道您这套代码，默认设置的T和D都是多少呢？ ![image](https://private-user-images.githubusercontent.com/67531605/377459545-86cda677-0f4c-4660-af78-c83899cdbd8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDk1NDgsIm5iZiI6MTcyOTkwOTI0OCwicGF0aCI6Ii82NzUzMTYwNS8zNzc0NTk1NDUtODZjZGE2NzctMGY0Yy00NjYwLWFmNzgtYzgzODk5Y2RiZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAyMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OTM1MmQ4MWJmZGQ5NmQwODYyYzJmZmZmZmVjNzY3ZTliNTFiMzQzOGRhNzUwODFjYjM5MjhjZjhhYjZkODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ND8ndqF5AdgCsQk4Nx8kmg2gvQmcp7Cj7Y8cN9RO82E) ![image](https://private-user-images.githubusercontent.com/67531605/377459652-97777ff9-b3ed-45c4-8f37-46241b44cc35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDk1NDgsIm5iZiI6MTcyOTkwOTI0OCwicGF0aCI6Ii82NzUzMTYwNS8zNzc0NTk2NTItOTc3NzdmZjktYjNlZC00NWM0LThmMzctNDYyNDFiNDRjYzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAyMjA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2Y4MjNmYTE0MmE3Y2Q2YzcxODcyYmQ5MmY5ODQzN2NhOGRlZDhjZGUyNDlkMmI2YmVlZGU5ZDAwOWVlNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NNt5FjkxKzw6RmjXVyKR1C804TF7TpWPyk3xKeKoePg)
> 
> 你好，你有跑通这个代码吗？请问它的训练时间是多少啊

你好，单张A100上训练，一个epoch大概是45分钟(s尺寸模型)
