### ISSUE TITLE
请问训练时间

### ISSUE THREAD

**Issue by zhangfzR** [BICLab/SpikeYOLO#13]
你好，我使用4090训练模型，但是这个跑的有点慢，跑一个epoch 要一个多小时，我想请问一下你们当时训练需要多久啊？

**Comment by XinhaoLuo666** [comment]
你好，单张A100上训练，一个epoch大概是45分钟(s尺寸模型)

**Comment by zhangfzR** [comment]
> 你好，单张A100上训练，一个epoch大概是45分钟(s尺寸模型)

你好，在你的文章fig.3中，说training的时候是使用integer进行乘加运算，而在inference的使用会按照最大的integer展开，只有加法运算。但是我在code中发现training和validate过程中都是MAC，我想问一下文中所说的inference的AC运算是在哪实现的呢？

**Comment by XinhaoLuo666** [comment]
代码里没有实现将整数转化为脉冲序列的函数，因为在GPU上这不会带来推理加速或能耗优势。但这很好实现，比如说，只需要”把一个3变成3个1”

**Comment by XinhaoLuo666** [comment]
代码里没有实现将整数转化为脉冲序列的函数，因为在GPU上这不会带来推理加速或能耗优势，反而会增大显存占用。在我们部署到神经形态芯片上时我们将其转化为纯AC运算，但那部分函数并不在这个代码中。其实这个转化很好实现，只需要根据D，把T,C,H,W的矩阵扩展为T,D,C,H,W矩阵，每个D序列对应原来的整数
