### ISSUE TITLE
Running and example with sample data and understanding the spike neuron usage and reset 

### ISSUE THREAD

**Issue by gwgknudayanga** [BICLab/SpikeYOLO#18]
Hi,

Could you please help me with the followings related to the code?

1. you have mentioned  2 files ( train_SpikeYOLO.py and test_SpikeYOLO.py) to train and test respectively. But those two files are not available. Are there any missing stuff?
2. Also you are using functional.reset_net(model) which is from spikingjelly. But you are not using any neurons from spikingjelly package as you used your custom neuron 'mem_update'. Then why are you using functional.reset_net ? What is the importance of it? 
3. Also, YOLO( ) model accept .yaml config file as constructor argument. How can we pass '.pt' saved checkpoints at the test time?
4. Are there any encoded/prepared input data that you used so that initially we can feed them to the code base and get some initial familiarization?
5. In snn_yolov8.yaml, I can see backbone and head parts and they are parsed with parse_model in tasks.py to form the model. But where is the 'Neck' module is implemented(seems it is also in the head defintion) ? 
6. Did you do mosaic augmentation even for the prophesee GEN1 DVS data? It is better if we can have the dataset class that you used to load the data for spiking neural network.
7. In  'SpikeDFL(nn.Module)', those there is a spike neuron defined, it seems it is not used. So it is same as Normal DFL without any spiking, isn't it?

Thank you.

Best Rgds,
Udayanga

**Comment by gwgknudayanga** [comment]
Thanks for the reply.
But when i am going to run the train with snn_yolov8.yaml i am getting following error. 
SyntaxError: snn_yolov8.yaml 'train:' key missing ❌.
'train' and 'val' are required in all data YAMLs.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/atiye/SpikeYOLO/train.py", line 12, in <module>
    model.train(data="snn_yolov8.yaml",device=[0],epochs=300)  # train the model
  File "/home/atiye/SpikeYOLO/ultralytics/engine/model.py", line 336, in train
    self.trainer = (trainer or self._smart_load('trainer'))(overrides=args, _callbacks=self.callbacks)
  File "/home/atiye/SpikeYOLO/ultralytics/engine/trainer.py", line 124, in __init__
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset 'snn_yolov8.yaml' error ❌ snn_yolov8.yaml 'train:' key missing ❌.
'train' and 'val' are required in all data YAMLs.

I used "model.train(data="snn_yolov8.yaml",device=[0],epochs=300)  " as coco.yaml is not available.

**Comment by gwgknudayanga** [comment]
Thank you for your reply. Please provide the dataset.py class for Prophesee GEN1 DVS data loading also.

**Comment by XinhaoLuo666** [comment]
We will upload the GEN1 dataset and processing method in a few weeks
