### ISSUE TITLE
 Questions Regarding Model Parameters and Training Configuration

### ISSUE THREAD

**Issue by KirinZheng** [BICLab/SpikeYOLO#22]
Thank you for sharing your excellent work and the open-source code! I have a couple of questions regarding the model parameters and training configuration:

1. I loaded the spikeyolo-L model version from your code and observed that the model parameters are approximately 65M. However, in your paper, the parameters for this model are reported as 68.8M, a difference of about 3M. Could this discrepancy be due to an issue in the snn_yolov8.yaml configuration file, or is there another reason for this difference?

2. To reproduce the results on the COCO-17 dataset, I followed the settings described in the paper. In the default.yaml configuration file, I set lr0 to 0.01 and lrf to 0.004. Are these the correct values? Additionally, should I keep other training parameters unchanged?

I appreciate your clarification and look forward to your response!

**Comment by XinhaoLuo666** [comment]
Thank you for your question
1. Sorry for not clarifying this in the code documentation. When the model size is l/x, the expansion factor of the last MS_convblock channel of the detection head becomes 2 (1 in the s and m models), which results in a parameter quantity difference of about 3M. We will clarify this issue in a future update and upload the 69M model .
2. Yes, you don't need to make modifications to the hyperparameters

**Comment by XinhaoLuo666** [comment]
Thank you for your question

Sorry for not clarifying this in the code documentation. When the model size is l/x, the expansion factor of the last MS_convblock channel of the detection head becomes "2" (which is “1” in the s/m size models), which results in a parameter quantity difference of about 3M. We will clarify this issue in a future update and upload the 69M model .
Yes, you don't need to make modifications to the hyperparameters
