### ISSUE TITLE
Questions about Re-parameterization Design.

### ISSUE THREAD

**Issue by jikerWRN** [BICLab/SpikeYOLO#24]
Hi, thank you for your awesome work!

I have a question regarding the Re-parameterization Design discussed in your paper. Based on the experimental results, it appears that the Re-parameterization Design improves the method's performance. However, the Re-parameterization should be an equivalent transformation, why does it lead to an increase in accuracy?

I look forward to your reply!

**Comment by XinhaoLuo666** [comment]
Thank you for your question. In ablation experiments, what we refer to as "removing  Re-parameterization convolutions" is equivalent to adding I-LIF neurons to multiple convolutions, which in turn leads to a decrease in accuracy.
