### ISSUE TITLE
There seem to be something wrong with power consumption calculation

### ISSUE THREAD

**Issue by Qiuyu-Li276** [BICLab/SpikeYOLO#25]
Leaving aside the rest, as for MS_CnvBlock, there are a total of 3 convolutions in the RepConv of MS_CnvBlock, and it seems that the latter two have not been included in the calculation. Moreover, these latter two seem to be MAC operations, and the power consumption involved cannot be ignored. Why not consider them?

**Comment by Qiuyu-Li276** [comment]
> As we mentioned in the paper, convolution here is a reparametric convolution, that is, it is reparameterized into a convolution and then computation is performed when it is re-inferred. Since reparameterization only needs to be performed once, there is only AC and no MAC for inference.
This is the reparameterized convolution at the end of MS_ConvBlock, but there is a SepConv at the beginning, and there is a PWConv and a DWConv at the end of SepConv.  There is no activation layer between the two conv, so DWConv should be counted as EAC, right? This doesn't seem to involve reparameterization operations in SepConv.
![image](https://github.com/user-attachments/assets/b7f975fa-57f1-45ac-89c2-76f1d10109af)

**Comment by XinhaoLuo666** [comment]
感谢您的关注，在SepConv中，DWConv和PWConv同样被重参数化为一个卷积
