### ISSUE TITLE
A question about the training method using I-LIF

### ISSUE THREAD

**Issue by caojiahui-ai** [BICLab/SpikeYOLO#3]
Thanks for the new spike neurons, but I wonder why using I-LIF for training is called “direct training”. I-LIF still has MACs during training, which feels more like a compromise between ANN2SNN and directly trained SNN.

**Comment by XinhaoLuo666** [comment]
Thanks for your question. Most of the methods for direct training of SNNs, such as LIF neurons, use the gradient substitution function method, which also has MAC in the training process, but does not include MAC in the inference process. It's the same with our I-LIF.
