### ISSUE TITLE
One problem is that he snn_yolov8s.yaml configuration file cannot be found

### ISSUE THREAD

**Issue by Cocatric** [BICLab/SpikeYOLO#4]
Hello, I am a beginner, your team's work is really great, but when I run your code, I can not find the snn_yolov8s.yaml model configuration file in the file list, may I ask is this snn and yolo combined model? Code integrity？
![image](https://github.com/user-attachments/assets/1ad882e5-0ebd-457c-85eb-1013bdd5b58d)

**Comment by Cocatric** [comment]
Oh,sorry.I have found it.

**Comment by Clluop** [comment]
i have the same question
