### ISSUE TITLE
About the environment

### ISSUE THREAD

**Issue by icypear** [BICLab/SpikeYOLO#6]
hi, could you please reveal the code environment for the reproduction? Such as the version of python, cuda? Thank you so much!!

**Comment by XinhaoLuo666** [comment]
> hi, could you please reveal the code environment for the reproduction? Such as the version of python, cuda? Thank you so much!!

We have already uploaded the environment config "environment.yaml".

**Comment by icypear** [comment]
> > hi, could you please reveal the code environment for the reproduction? Such as the version of python, cuda? Thank you so much!!
> 
> We have already uploaded the environment config "environment.yaml".

Thank you so much!! very helpful!!
