### ISSUE TITLE
参数量计算方面

### ISSUE THREAD

**Issue by jiaduob** [BICLab/SpikeYOLO#8]
你好，感谢你们的工作，我在自己的数据集上成功复现SpikeYOLO并取得了不错的效果。但是同时我有一些疑问希望得到解答。

#### 1.参数量计算方面

在paper中是这样的（配置文件中有5种scale分别是nslmx，这里是少了哪一种？）：
![SpikeYOLO参数量-论文](https://github.com/user-attachments/assets/93eae167-4718-4bf4-8493-875656dd839b)

在项目中的配置文件snn_yolov8.yaml中是这样描述的：
![SpikeYOLO参数量-配置文件](https://github.com/user-attachments/assets/781b9783-0388-4083-9e12-2cdf4ec621df)

ultralytics的自带的功能进行scale为s的计算：
![SpikeYOLO参数量-计算](https://github.com/user-attachments/assets/f56b05a4-7674-45d7-a5e2-8ab2fbec34f1)

请问哪一种是准确的？

**Comment by XinhaoLuo666** [comment]
您好，论文中的参数量和ultralytics的自带计算得到的结果是正确的，项目配置文件中的参数量是原版yolov8的参数量，我们将在后续版本中删除。我们没有训练scale为x的模型。

**Comment by jiaduob** [comment]
非常感谢您的回复
